# Site
name: "Azure Guru - Microsoft Azure stories from Cloud Architects"
description: "Azure Guru - is a group of creative and passionate enthusiasts and technologists working (or former) at @Microsoft with a primary focus on @Azure! We strive to share what we have learned with everyone in the world!"
meta_description: "Independed blog by Cloud Architects"
logo: 'assets/images/layout/logo.png'
small-logo: 'assets/images/layout/small-logo.png'
favicon: 'assets/images/layout/small-logo.png'
baseurl:
google_site_tag: 'UA-132881488-1'
disqus: 'azcee'
mailchimp-list: ''

permalink: pretty


# Authors
authors:
  evgeny:
    name: Evgeny
    display_name: Evgeny Rudinsky
    gravatar: f246b5cca97060fa8bb803b34c9aee2a
    twitter: https://twitter.com/evgenyrudinsky
    linkedin: https://www.linkedin.com/in/evgenyrudinsky/
    description: "Cloud Architect @ Nordcloud"

  sergeype:
    name: Sergey
    display_name: Sergey Pechenkin
    gravatar: a9488f7bf8fc60626f7a3cc2f2925941
    twitter: https://twitter.com/Sergey14836406
    linkedin: https://www.linkedin.com/in/sergey-pechenkin-21994512/
    description: "Cloud Architect @ Microsoft"
    
    


# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
  - jekyll-sitemap
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge

# Custom vars
version: 0.1

github:
  repo: https://github.com/AzCEE/azcee.github.io

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - output
  - Gruntfile.js
  - package.json
  - tasks.py
  - node_modules
  - dist