# Site
name: "AzCEE Team pages - Microsoft Azure stories by TSPs"
description: "AzCEE is a group of creative and passionate enthusiasts and technologists working (or ex-) as Technology Solutions Professional (TSP) @Microsoft with core focus on @Azure! We're keen to share what we've learnt with anyone in the World!"
meta_description: "Independently driven blog by members of Azure TSP"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl:
google_analytics: ''
disqus: 'azcee'
mailchimp-list: ''

# Authors
authors:
  evgeny:
    name: Evgeny
    display_name: Evgeny
    gravatar: f246b5cca97060fa8bb803b34c9aee2a
    email: evgeny.rudinsky@gmail.com
    web: https://erudinsky.com
    twitter: https://twitter.com/evgenyrudinsky
    description: "Azure Apps & Infra TPS"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge
